### ISSUE TITLE
First time opening on windows...

### ISSUE THREAD

**Issue by jonaaa20** [olliethepikachu/MusicDownloader#5]
Using Windows 10 Here, did all the steps and then...

`Traceback (most recent call last):
  File "DeezerDownload.py", line 34, in <module>
    import requests
ImportError: No module named requests`

any ideas?

**Comment by MiniCheese26** [comment]
Not sure if i actually fixed anything or just created more problems, but i ran this in cmd

`pip install requests`

and now I've gotten to a new error

`Traceback (most recent call last):
  File "E:\Deezloader\MusicDownloader-master\DeezerDownload.py", line 39, in <module>
    from tkFileDialog import askopenfilename as openfile
  File "C:\Python27\lib\lib-tk\tkFileDialog.py", line 43, in <module>
    from tkCommonDialog import Dialog
  File "C:\Python27\lib\lib-tk\tkCommonDialog.py", line 11, in <module>
    from Tkinter import *
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
  File "C:\Python27\lib\lib-tk\FixTk.py", line 68, in <module>
    import _tkinter
ImportError: DLL load failed: %1 is not a valid Win32 application.`

Pretty long error

Just to note, i have no experience with Python and i'm on Windows 8.1

**Comment by jonaaa20** [comment]
Ugh, to be honest, Python sucks, fixed here too with this command, and got the same error as yours... geez how i hate python.

**Comment by olliethepikachu** [comment]
I'll look into it when I get home.

**Comment by olliethepikachu** [comment]
Uhh, it seems as if that is a purely Python problem... Weird. For now, the best I can come up with to fix it (apart from reinstalling the right Python architecture), is to go into the code and change a few things. The only downside, is that the CSV downloader (option 1 when you start the downloader up) will not work.

Ready?

If you open DeezerDownload.py in Notepad++ (or Notepad for that matter), go to the line which says `from tkFileDialog import askopenfilename as openfile` (near the start, line 39) and remove it. Then go on your way.

**Comment by olliethepikachu** [comment]
Closed due to inactivity.
