### ISSUE TITLE
Could not find the song; perhaps it isn't available here?

### ISSUE THREAD

**Issue by mainczjs** [olliethepikachu/MusicDownloader#7]
Hey,
just come back to run another test, and this is what I got for every song:

`Could not find song; perhaps it isn't avaliable here?`

Did they change something server side?

**Comment by olliethepikachu** [comment]
Hmmmm. Perhaps it isn’t available where you are? xD

But, seriously, try downloading something else, for instance “all we know” by “the chainsmokers” (that song because it will probably work).

**Comment by olliethepikachu** [comment]
Also, are you running the binaries or the self-compiled version?

**Comment by mainczjs** [comment]
I ran the python script using a freshly set up python2.7 environment. The dependencies were installed through pip and avbin was installed using it's binaries
But nervermind, problem was solved by recreating the downloads-folder, the script was expecting... ;)

**Comment by olliethepikachu** [comment]
Great! What was wrong with the Downloads folder?

**Comment by mainczjs** [comment]
It was not existent...

**Comment by olliethepikachu** [comment]
Ah.
